language: python
python:
  - "2.7"
  
install:
  - sudo apt-get install python-tk
  - pip install nvpy
  - sudo apt-get install python-stdeb fakeroot python-all
  
script:
  - cd deb-package-builder
  - ls -a
  - python setup.py --command-packages=stdeb.command deb_dist
  - sudo dpkg -i deb-package-builder/deb_dist/python-batch-renamer-cli_1.0.1-1_all.deb 
  - python -c "import batch_renamer_cli"
  
